### ISSUE TITLE
[BUG REPORT] Example_groups is empty

### ISSUE THREAD

**Issue by sachin21** [tmm1/test-queue#59]
# Environment
- Rails: 4.2.6
- RSpec: 3.4.0

## My test-queue runner
```
#!/usr/bin/env ruby

ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)

require 'test_queue'
require 'test_queue/runner/rspec'

 --- Temporary solusion ---
 class TestQueue::TestFramework::RSpec
   def suites_from_file(path)
#   ::RSpec.world.example_groups.clear Comment out this line.
     load path
     split_groups(::RSpec.world.example_groups).map { |example_or_group|
       name = if example_or_group.respond_to?(:id)
                example_or_group.id
              elsif example_or_group.respond_to?(:full_description)
                example_or_group.full_description
              else
                example_or_group.metadata[:example_group][:full_description]
              end
       [name, example_or_group]
     }
   end
 end
# ------

class MyTestRunner < TestQueue::Runner::RSpec
  def after_fork(num)
    database_num = num > 1 ? num.to_s : ''
    ActiveRecord::Base.configurations['test']['database'] << database_num
    ActiveRecord::Base.establish_connection(:test)
  end

  def prepare(concurrency)
    database_name = ActiveRecord::Base.configurations['test']['database']
    concurrency.times do |num|
      database_num = num > 1 ? num.to_s : ''
      ActiveRecord::Base.configurations['test']['database'] = database_name + database_num
      ActiveRecord::Tasks::DatabaseTasks.drop_current
      ActiveRecord::Tasks::DatabaseTasks.create_current
      ActiveRecord::Tasks::DatabaseTasks.load_schema_current
    end
    ActiveRecord::Base.configurations['test']['database'] = database_name
  end
end

MyTestRunner.new.execute
```
I encountered this error:
```
rspec-core-3.4.4/lib/rspec/core/example_group.rb:370:in `find_and_eval_shared': Could not find shared context "apollo v2 api" (ArgumentError)
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:331:in `include_context'
        from /home/sachin21dev/Projects/github.com/username/product_name/spec/models/api/apollo/v2/adjacent_item_spec.rb:4:in `block in <top (required)>'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:385:in `module_exec'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:385:in `subclass'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/example_group.rb:255:in `block in define_example_group_method'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/dsl.rb:43:in `block in expose_example_group_alias'
        from /home/sachin21dev/Projects/github.com/username/product_name/spec/models/api/apollo/v2/adjacent_item_spec.rb:3:in `<top (required)>'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `each'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in `setup'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:38:in `perform_at_exit'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:24:in `block in autorun'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/test-queue-0.3.1/lib/test_queue/runner.rb:245:in `fork'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/test-queue-0.3.1/lib/test_queue/runner.rb:245:in `block in spawn_workers'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/test-queue-0.3.1/lib/test_queue/runner.rb:242:in `times'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/test-queue-0.3.1/lib/test_queue/runner.rb:242:in `spawn_workers'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/test-queue-0.3.1/lib/test_queue/runner.rb:188:in `execute_internal'
        from /home/sachin21dev/Projects/github.com/username/product_name/vendor/bundle/ruby/2.3.0/gems/test-queue-0.3.1/lib/test_queue/runner.rb:122:in `execute'
```

So I made temporary solution that is:
```
class TestQueue::TestFramework::RSpec
  def suites_from_file(path)
# ::RSpec.world.example_groups.clear 
    load path
    split_groups(::RSpec.world.example_groups).map { |example_or_group|
      name = if example_or_group.respond_to?(:id)
               example_or_group.id
             elsif example_or_group.respond_to?(:full_description)
               example_or_group.full_description
             else
               example_or_group.metadata[:example_group][:full_description]
             end
      [name, example_or_group]
    }
  end
end

```

Why do you clear example_groups? `::RSpec.world.example_groups.clear` is cause in this case.
It looks like delete needed shared_contexts before `include_context` is executed.

**Comment by aroben** [comment]
@sachin21 I think https://github.com/tmm1/test-queue/pull/57 fixes this, but I see I forgot to publish a new release after merging that. I just published [v0.4.0](https://github.com/tmm1/test-queue/releases/tag/v0.4.0); can you give that a try?

**Comment by aroben** [comment]
Please reopen this issue if you're still having problems.

**Comment by aroben** [comment]
And thank you for the very clear bug report!

**Comment by sachin21** [comment]
@aroben Thank you for the quick response!
It works for me. But the new problem has occurred. Could you check this issue? 

https://github.com/tmm1/test-queue/issues/60

**Comment by sachin21** [comment]
@aroben I found that this [issue's](https://github.com/tmm1/test-queue/issues/60) the root cause.
I think `example_groups.clear` is clear all examples. So MyTestRunner will no execute examples.

Could you re-open this?
